### ISSUE TITLE
AntiMarker

### ISSUE THREAD

**Issue by Tom-TBT** [eulerlab/QDSpy#15]
Hi Thomas,
I fetch the new version and I saw that anti marker was not working. I think you accepted this modif since I saw it around the code. I notice that there is only one thing missing:
In QDSpy_core_presenter.py, line 485:
if self.Conf.markShowOnScr:
if sc[stm.SC_field_marker]:  
self.Batch.add_rect_data(self.markerVert)

But it miss the printing of the antimarker and should be like that:
if self.Conf.markShowOnScr:
if sc[stm.SC_field_marker]:  
self.Batch.add_rect_data(self.markerVert)
else:
self.Batch.add_rect_data(self.antiMarkerVert)

I think the best is that you change it directly if you agree with it.

Cheers,
Tom

**Comment by teuler** [comment]
Thanks for the hint. I fixed it according to your suggestion.
Best
Thomas
