### ISSUE TITLE
QDSpy documentation

### ISSUE THREAD

**Issue by Tom-TBT** [eulerlab/QDSpy#18]
Hi Thomas,
I was installing on a fresh computer QDSpy. I followed the installation instruction on http://qdspy.eulerlab.de/installation.html, and one install was missing from there:

pip install serial

I forgot to note the error and from which script the error came from, but I think it's one of the digital I/O thing.
Anyway, just installing this additional package solved my problem.

Cheers,
Tom

**Comment by teuler** [comment]
Thanks for the hint. I'll add this information to the next update.
I usually install "pip install pyserial". 

Best
Thomas
