### ISSUE TITLE
Question on the water video stimulus

### ISSUE THREAD

**Issue by Tom-TBT** [eulerlab/QDSpy#32]
Hi Thomas,
I'm interested in the water.avi video, but I need to modify it slightly. I can do that in Fiji for example but then exporting it with jpeg compression gives a lower quality.

Is it a video you found online? Is it possible to generate or obtain a longer one with a higher quality and/or resolution? (with png compression maybe)

I want to remove the red component from the video, and make it longer. I saw that I can concatenate video but I'd prefer not to, to avoid correlations in the stimulus.

Thanks,
Tom

**Comment by teuler** [comment]
Hi Tom,

here is the script that generates such movies:
https://www.dropbox.com/s/do82izc6l7bpsju/waterStimuli.py?dl=0
If you use it, please acknowledge the original source.

Best
Thomas

P.S.: For displaying such movies, you can also use the video commands instead of the movie commands.

**Comment by Tom-TBT** [comment]
Thank you Thomas. 
by the original source, you mean github.com/atlab ?

Best,
Tom

**Comment by teuler** [comment]
Yes. Of course, Luke would probably also happy for being mentioned for the Python version ;-)

**Comment by teuler** [comment]
Btw. I’ll soon release a new experimental version with LCr pattern mode support. Do you have any changes that should be integrated into the master soon?

**Comment by Tom-TBT** [comment]
No, I haven't done modifications recently. 
And yes of course, Luke will be mentioned, that's a huge time saving for me to have the code in python!
