### ISSUE TITLE
Stimulus recording

### ISSUE THREAD

**Issue by jonathanoesterle** [eulerlab/QDSpy#37]
I added some code to make the stimulus recording (i.e. save the stimulus to a file) functional. I was wondering if I should make a pull request for this (then I would have to clean the code a bit, first).

The code is implemented such that:
Every n-th frame (set by the user) is stored to a (downsampled, set by the user) PIL image. At the end of the stimulus all PIL images are stacked to a 4d-numpy-uint8-array and saved to a pickle file.

**Comment by teuler** [comment]
Sure. Make it a pull request in the experimental branch. Thanks.
